version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cv-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - cv-network

networks:
  cv-network:
