name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 16.171.41.127
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "cv-website" ]; then git clone https://github.com/bemird/cv-website.git; fi
            cd cv-website
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
